version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: second-me-backend
    restart: unless-stopped
    ports:
      # Backend service port mapping
      - "8002:8002"
      # Additional 8080 port mapping
      - "8080:8080"
    volumes:
      # Data directory mapping
      - ./data:/app/data
      # Logs directory mapping
      - ./logs:/app/logs
      # Run directory mapping
      - ./run:/app/run
      # Resources directory mapping
      - ./resources:/app/resources
      # .env file mapping
      - ./.env:/app/.env
    environment:
      # Environment variables
      - LOCAL_APP_PORT=8002
    deploy:
      resources:
        limits:
          # Set container memory limit to 24GB
          memory: 24G
        reservations:
          # Memory reservation
          memory: 6G
    networks:
      - second-me-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: second-me-frontend
    restart: unless-stopped
    ports:
      # Frontend service port mapping
      - "3000:3000"
    volumes:
      # Logs directory mapping
      - ./logs:/app/logs
      # Resources directory mapping for frontend
      - ./resources:/app/resources
    environment:
      # Environment variables
      - VITE_API_BASE_URL=http://backend:8002
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          # Set container memory limit to 8GB
          memory: 8G
        reservations:
          # Memory reservation
          memory: 2G
    networks:
      - second-me-network

networks:
  second-me-network:
    driver: bridge
